### ISSUE TITLE
Baseline model can't converge 

### ISSUE THREAD

**Issue by Haoyayu** [bozliu/CelebA-Facial-Attribute-Recognition-Challenge#3]
Hi, thanks for sharing your code! I also train this model (https://github.com/d-li14/face-attribute-prediction), which is the baseline in your work. But the model seems like not converge fast as following. 
<img width="528" alt="image" src="https://user-images.githubusercontent.com/44563504/220609341-c0b028fb-93dd-4240-b742-8d8bda2fe958.png">
I also use the img_align_celeba as training data and all training parameters used are default as baseline model. Could you know the reason why my model not converge?

**Comment by bozliu** [comment]
If you need to report an issue related to the baseline repository you trained, please create it under that repository instead of creating it here.
